server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Это лечит 404 при перезагрузке страниц
    }

    # Прокси для API (чтобы не было проблем с CORS)
    location /api/ {
        proxy_pass http://api:3000/; 
    }
}
